### ISSUE TITLE
Update Abstracts, digests and impact statements page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#189]
- [x] 'If the biological system (species names or broader taxonomic groups if appropriate) is not mentioned in the title, it must be included in the abstract.' - after production/editorial meeting, update page to move this instruction to copyediting page if required
- [x] 'Subheadings are discouraged in abstracts, except for medical submissions' - update page after production/editorial meeting outcome

**Comment by FAtherden-eLife** [comment]
Please note the discussion [here](https://elifesciences.slack.com/archives/CAJ0M8KST/p1625652719002600).

`medicine-abstract-conformance-2` has been downgraded to a warning as a result. It should only be ignored if there is a note from eJP about the article structure/abstract. Otherwise it should be checked with Editorial.
