### ISSUE TITLE
Create Data availability page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-gitbook#5]
- [x] Create page 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents (including dataset assignment spreadsheet)
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Becky approved page
- [x] Melissa approved page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
@naushinthomson @FAtherden-eLife @Melissa37 @bcollins14 - please could I get your review on https://app.gitbook.com/@elifesciences/s/schematron/article-details/content/data-availability

Notes:
* I've not written up the action for data-openneuro-test-2 yet because I wanted to check whether we still wanted to allow both DOIs and archives for OSF datasets?
* Please let me know if the table of common databases works - if I have to change that, I want to get that out of the way BEFORE I start adding any missing examples
* Speaking of, do we want to update the rules with proper assigning authorities for everything currently allowed as 'other' and get Exeter to update Kriya? (Won't be able to do this for everything, since some of them have multiple authorities, but we can get a few more in)
* I ended up duplicating the text for a lot of the similar messages. I wasn't quite sure how we'd do the headings otherwise and Exeter will need to refer to the warning messages for each case. Also, some of those tests are not quite identical in what they check so . . .

**Comment by naushinthomson** [comment]
Text change suggestions: 
'Links that just go to the the landing page for a dataset will need to be replaced.' to 
'Links that just go to the database homepage will need to be replaced.'

'In both these cases, 'on request' data is permitted with the approval of the editors handling the article. This approval will be indicated in the Production Comments if it has been received prior to export from the submission system; if approval is outstanding, this should also be indicated in these comments.' to
'In both these cases, the editors handling the article will have approved the data to be ‘on request’. If the editors gave their approval before the article was exported from the submission system, this will be shown in the Production Comments. If they have yet to do this, this should also be indicated in these comments.’ Or something similar (in case it’s hard to understand if English isn’t your first language?)

‘An author query was left requesting further details and once these were provided, the main-text statement was removed and the text was combined with the Data availability statement’ – should we clarify which author query was left just to be completely clear?
For back-test-3 can the action be changed to
‘This error will fire if there is no data availability section <sec sec-type="data-availability"> present in the <back> element for an article, or if there is more than one section of this type present. The section will need to be added in, or the extra sections will need to be removed.’ Also is this a rare error that we want to be notified about? 

Can the action of back-test-10 be changed to 
‘This warning will fire if there is no <sec sec-type="data-availability"> present in the <back> element for an article, or if there is more than one section of this type present. Extra sections will need to be removed but if this is a new version of a very old article, a data availability section shouldn’t be added.’ Also can we specify how old the article should be for us to not add a DAS?

das-elem-citation-child-1 change the action to:
‘The only formatting elements allowed for a dataset title (<data-title>) or database name (<source>) are formatting tags for italics, superscript and subscript. Any other formatting should be removed and any hyperlinks in these fields should be changed to plain text. XXXXXX will be the child and parent elements, respectively.’ Can we clarify the child and parent elements in non-xml terminology?

Questions:
In the ‘Data available on request and on acceptance’ sections, should we make it clear what we expect Exeter to do specifically? As it stands it seems to be addressed to eLife staff only?
‘Once the authors have responded, the entry for the whole database can be replaced with one or more specific datasets, or removed entirely in favour of a citation or URL link in the main text.’ – Do we have guidance on when we want references in the reference list vs url links vs dataset references?
In the action for das-elem-cit-3 and 4, should an author query also be left to ask the author to confirm the details are correct? 
Should we indicate somewhere what we want Exeter to do if they come across a database not listed in the examples section? 
For the action of data-ref-given-names-test-1 do we want to mention a case where this warning can be ignored?
das-elem-cit-4 – The reference in position XX of the data availability section has a pub-id (XXXXXX) which is the same as another dataset reference in that section. This is very likely incorrect. Dataset reference pub-id should be distinct.
Should we clarify when this is ok to ignore?
Can the action of das-elem-citation-year-1 be reworded to reduce the xml terminology?
For the xml structure errors in general, is it easy enough to remove extra elements when they are there in error?
I’m not sure I understand the action of das-elem-cit-1 and 2. How do we add a specific-use attribute in?
General question – should ‘data availability statement’ have the capitalised ‘D’ throughout? I’m not sure if it should but just checking!

@FAtherden-eLife Schematron message changes:
Should the text of final-das-elem-data-title-1 be changed to ‘The reference in position XX of the data availability section does not have a title (no data-title). Please ensure to add it **in**.’ to match the text of other similar messages?
Should the text of data-edatashare-test-3 – be changed to Data reference with the title 'XXXXXX' has **an** Edinburgh DataShare type doi - XXXXXX, but the assigning authority is not 'Edinburgh University', which must be incorrect.
Should the text of das-pub-id-1 – be changed to ‘Each pub-id element must have **a** @pub-id-type with one of these types: accession, archive, or doi.’

**Comment by FAtherden-eLife** [comment]
Thanks @JGilbert-eLife, looks good - just a handful of (mostly minor) points from me

1. Question (presumably for @Melissa37) - what are we expecting to happen in the new workflow when data is 'available on request'? Exeter to query us (and us to query editorial) before it's sent out to author? Exeter to add in a query? Or for us to deal with it at Post-author?

2. @JGilbert-eLife - Database examples table - there's a column for URLs and column for DOIs. I get that it would be good to indicate what URLs we can expect for dataset with dois, but does including them leave room for confusion? If there's a doi, we obviously would always want the doi link to be used instead.

3. Can we get rid of `dx.` in doi link examples?

4. A bit of pedantry - for `data-openneuro-test-1` and `data-synapse-test-1` - this text:
> This warning indicates that the database name for a dataset is not the one expected based on the URL provided.

needs changing to:

> This warning indicates that the database name for a dataset is not the one expected based on the DOI provided.

5. > I've not written up the action for data-openneuro-test-2 yet because I wanted to check whether we still wanted to allow both DOIs and archives for OSF datasets?

Can't remember why we allowed both in the test. I've found two examples of links (rather than dois) from the archive - 1 of these no longer works as a link, and the other has a doi. Perhaps we should just allow dois then?

6. Should we specify that `back-test-3` and `back-test-10` only apply to research articles (which aren't Scientific Correspondences)?

7. > In research content, the data availability statement is mandatory.
...
Feature content does not require a data availability section.

Is it worth specifying explicitly that this Feature templates 5s require DASs - or is that implied (since they are treated as research content)?

8. @naushinthomson, @JGilbert-eLife 
> Also can we specify how old the article should be for us to not add a DAS?

31st May, 2018 is the cut off. Although some before that might have DASs, all after that date should definitely have one.
`back-test-3` will fire if the pub-date is greater than (meaning after) 2018-05-31.
`back-test-10` will fire if the pub-date is less than (meaning before) or equal to 2018-05-31.

**Comment by FAtherden-eLife** [comment]
> @FAtherden-eLife Schematron message changes:
Should the text of final-das-elem-data-title-1 be changed to ‘The reference in position XX of the data availability section does not have a title (no data-title). Please ensure to add it in.’ to match the text of other similar messages?
Should the text of data-edatashare-test-3 – be changed to Data reference with the title 'XXXXXX' has an Edinburgh DataShare type doi - XXXXXX, but the assigning authority is not 'Edinburgh University', which must be incorrect.
Should the text of das-pub-id-1 – be changed to ‘Each pub-id element must have a @pub-id-type with one of these types: accession, archive, or doi.’

Thanks @naushinthomson - will update.

**Comment by Melissa37** [comment]
The JATS4R Data citations recommendation has gone out for public review on V2:
https://docs.google.com/document/d/1Mph70pGM2H-NsFEU48MFmPKtE0HiQrRf9UD73kZBADQ/edit

Things to note:
>@assigning-authority on <pub-id> . When the given type of identifier can be assigned by more than one organisation (e.g. DOIs minted by CrossRef or DataCite) and the organisation registering the identifier is known, include the @assigning-authority attribute on the <pub-id> element. For example, a DOI that is assigned by CrossRef should have “doi” as the @pub-id-type, and “crossref” as the @assigning-authority. For many types of identifiers, there is only one assigning authority. For example, PubMed IDs are always assigned by the National Library of Medicine. In these cases @assigning-authority is not necessary.

Talking on the JATS4R steering committee - this is not necessary at all and most people won't do it. I think we can ditch it completely, as we're doing it wrong anyhow. For example we add assigning authority for Figshare as figshare, but it's actually Datacite. Likewise the DOIs used by Europe PMC are Crossref.

>'''<source>ArrayExpress</source>
<pub-id pub-id-type="accession" xlink:href="https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-3649/">E-MTAB-3649</pub-id>'''

From the JATS guidance:
>archive | Generic identifier type for an identifier assigned by an archive or other repository (generally used with elements <object-id>, <issue-id>, and <volume-id>)

We're using it wrongly and should not be using archive. If the identifier is part of the URL string then it's a PID and we should be using accession
I don't think it would be a bad thing if where we have an ID it's simply a DOI OR accession

The problems of being ahead of the times and trying to do things in the dark!

**Comment by Melissa37** [comment]
>The data availability section provides information on how to access the data used in or generated by the work being reported in an article. eLife strongly encourages authors to deposit any data they generate in a dedicated open repository so that it is available for further study and to allow the replication of their results, and to acknowledge any previously published datasets that they have used.

Question - data are VS data is - are we going with common usage of nowadays and not being strict about singular/plural usage of datum/data?

>and to acknowledge any previously published datasets that they have used
I think we should word this more strongly. It's to ensure previously published data sets that are re-used are given proper credit by adding them as references, which can be tracked.

**Comment by Melissa37** [comment]
in the What needs to be checked section

>Previously published datasets
The same rules apply as for generated datasets.

Do the same rules apply? For instance "See below for actions in cases where data is not yet available." Would they not be different actions?

**Comment by Melissa37** [comment]
>Year: This should be the year that the dataset was made publicly available. For generated datasets, be aware that this might not be the same as the year of publication for the current article.

This might not be the same for generated datasets too, it's not exclusive to previously published?

**Comment by Melissa37** [comment]
>Identifier: A unique string that can be used to identify the dataset. This may be a DOI, an accession number or simply an ID unique to the database in which the data has been stored.

Base on JATS4R rec, should we change this to:

Identifier: A unique string that can be used to identify the dataset. This may be a DOI or an accession number.

?

**Comment by Melissa37** [comment]
>pub-id-type: The type of identifier present. Chose from: accession, archive, doi. This cannot be left as 'other'. Guidance on which databases take which value for this field can be found here.
>assigning-authority: The organisation that assigned the identifier. Often the organisation that hosts/maintains the database. This can be set to 'other' if multiple organisations are involved or the authority is not on the list of allowed values. The values for common databases can be found here.

Change? Based on JATS4R

**Comment by Melissa37** [comment]
>The editor is the same for generated and previously published datasets

Suggest replacing the word Editor with something else (could be confused with academic/scientific editor! Or maybe that's just my brain :-)

**Comment by Melissa37** [comment]
>For example if the authors have simply added 'Smith et al.' or similar in the submission system, the full author list will need to be located and entered.

Are we being too anal here? It can be so so hard to find these details, should we just relax our procedures and allow et al in dataset references? 
Presumably, if it's a DOI Crossref or Datacite could be consulted for the details?

**Comment by Melissa37** [comment]
In section "Data available 'on request'"

>To ensure openness, eLife instead encourages authors to deposit all their data in a dedicated repository or a more general archive such as Dryad or figshare, where it will be available to anyone who wants it.

is it worth adding subject-specific in front of a dedicated repository?

**Comment by Melissa37** [comment]
>If approval for 'on request' data has not been indicated, the Production team should contact the Editorial team to establish whether they are working on this issue already and what action needs to be taken.

Is it worth stating that also sometimes these slip through unchecked by the editorial team and some we are the "backstop" and responsible for catching things that fall through the cracks?

**Comment by Melissa37** [comment]
>All data generated or analysed during this study are included in the manuscript and supporting files. Source data files will be made available upon acceptance

I've also seen that source files will also be uploaded on acceptance...and this needs to be checked too? and change the wording.

**Comment by Melissa37** [comment]
>If it is not possible to add the dataset(s) based on the information provided, either because it is incomplete , 

remove the space in front of the comma :-)

**Comment by Melissa37** [comment]
>Any link like this will need to be replaced with the final dataset URL before publication. If it is not possible to identify the final link based on the reviewer link or the given identifier, the author should be queried:
Please provide the final URL for this dataset.

Should this AQ also say ...and ensure the dataset is public by the time of publication?

**Comment by Melissa37** [comment]
>For example, in the following case, the Data availability statement was:
Data have been deposited on GEO under the accession number GSE140919. A source data file has been provided.
But an in-text statement mentioned additional data submitted to dbGAP:
The data for this study have been deposited in the database dbGAP. The sequenceing data can be found as GenBank GSE140919. Data can also be found in the included source file.
Since the authors did not provide details for their dbGAP dataset, the Production team first contacted Editorial to check if they were working on this already. The authors were then asked to provide the missing information but they responded that they had not, in fact, deposited data to dbGAP. The in-text statement was then deleted and the Data availability statement was retained as originally provided.

I wonder whether we can reduce communication loops somehow and just AQ rather than needing to go back to editorial?

**Comment by Melissa37** [comment]
linked to above comment

>In another instance, the Data availability statement was
All data generated or analyzed during this study are included in the manuscript and supporting files
while the in-text equivalent read
Representative segmented neurons for all presented neuron types will be available at Virtual Fly Brain (https://www.virtualflybrain.org).
An author query was left requesting further details and once these were provided, the main-text statement was removed and the text was combined with the Data availability statement:
All data generated or analyzed during this study are included in the manuscript and supporting files. Representative segmented neurons for all presented neuron types are available at Virtual Fly Brain (http://virtualflybrain.org/data/Lee_Lineage2020).

This is a new method of documenting. I thought we had been citing examples but not saying they had happened. I hope that makes sense? Maybe change to 

In another instance, the Data availability statement could be
while the in-text equivalent reads
Add an author query requesting further details and once these are provided, the main-text statement should be removed and the text combined with the Data availability statement:

Also, need to indicate which AQ to use

**Comment by Melissa37** [comment]
>The reference in position XX 

>The reference in position XXXXXX

Can we standardise the Schematron messages (or this doc so they are all the same number of Xs?

**Comment by Melissa37** [comment]
> The author should be asked by email to provide the missing details if they cannot be found using the other dataset information

Should we clarify that this is a production editor task and not a vendor or freelancer task?

**Comment by Melissa37** [comment]
>For example, if the URLS for two datasets are both 

The s on URLS should be lower case :-)

**Comment by Melissa37** [comment]
>For example, if the indentifiers for two datasets are both GSE135351, but the URLs are

Typo - indentifiers should be identifiers
